# This is a basic workflow to help you get started with Actions

name: Blog Post To Gist
on:
  push:
    branches:
      - publish/blog/**
    paths:
      - Blog/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_blog_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Extract File Path
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref }}
          regex: '[a-zA-Z0-9]+\/[a-zA-Z0-9-]+$'
      - name: Set Path Variable
        run: export POST_PATH='${{ steps.regex-match.outputs.match }}'
      - name: Print File Path
        run: echo $POST_PATH
      - name: Extract File Path
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match-2
        with:
          text: ${{ github.ref }}
          regex: '[a-zA-Z-0-9]+.md$'
      - name: Set Path Variable
        run: export FILE_NAME='${{ steps.regex-match.outputs.match }}'
      - name: Print File Path
        run: echo $FILE_NAME
      #- name: Publish To Gist
       # uses: exuanbo/actions-deploy-gist@v1
        #with:
         # token: ${{ secrets.GIST_TOKEN }}
          #gist_id: from_your_gist_url
          #gist_file_name: foo.bar
          #file_path: './Blog/${{ steps.regex-match.outputs.match }}.md'
    
  
